version: "3"
services:
  app:
    container_name: rtspapp
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      [mongo]
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"